From 21c7b62fa29520bb99cbed4a4d1e118065211e80 Mon Sep 17 00:00:00 2001
From: Himanshu <himanshu@cloudera.com>
Date: Tue, 28 Aug 2012 13:38:04 -0600
Subject: [PATCH 126/154] HBASE-6314 Fast fail behavior for unauthenticated user

Reason: Improvement
Author: Himanshu Vashishtha
Ref: CDH-6076
---
 .../org/apache/hadoop/hbase/ipc/SecureClient.java  |   19 ++++++++++++++++++-
 1 files changed, 18 insertions(+), 1 deletions(-)

diff --git a/security/src/main/java/org/apache/hadoop/hbase/ipc/SecureClient.java b/security/src/main/java/org/apache/hadoop/hbase/ipc/SecureClient.java
index e85bf42..720338f 100644
--- a/security/src/main/java/org/apache/hadoop/hbase/ipc/SecureClient.java
+++ b/security/src/main/java/org/apache/hadoop/hbase/ipc/SecureClient.java
@@ -40,6 +40,7 @@ import org.apache.hadoop.security.token.TokenSelector;
 import org.apache.hadoop.util.ReflectionUtils;
 
 import javax.net.SocketFactory;
+import javax.security.sasl.SaslException;
 import java.io.*;
 import java.net.*;
 import java.security.PrivilegedExceptionAction;
@@ -185,6 +186,14 @@ public class SecureClient extends HBaseClient {
      * again.
      * The other problem is to do with ticket expiry. To handle that,
      * a relogin is attempted.
+     * <p>
+     * The retry logic is governed by the {@link #shouldAuthenticateOverKrb}
+     * method. In case when the user doesn't have valid credentials, we don't
+     * need to retry (from cache or ticket). In such cases, it is prudent to
+     * throw a runtime exception when we receive a SaslException from the
+     * underlying authentication implementation, so there is no retry from 
+     * other high level (for eg, HCM or HBaseAdmin).
+     * </p>
      */
     private synchronized void handleSaslConnectionFailure(
         final int currRetries,
@@ -222,8 +231,16 @@ public class SecureClient extends HBaseClient {
             LOG.warn("Exception encountered while connecting to " +
                 "the server : " + ex);
           }
-          if (ex instanceof RemoteException)
+          if (ex instanceof RemoteException) {
             throw (RemoteException)ex;
+          }
+          if (ex instanceof SaslException) {
+            String msg = "SASL authentication failed." +
+              " The most likely cause is missing or invalid credentials." +
+              " Consider 'kinit'.";
+            LOG.fatal(msg, ex);
+            throw new RuntimeException(msg, ex);
+          }
           throw new IOException(ex);
         }
       });
-- 
1.7.0.4

